name: xeus-nelson-kernel
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab >=3,<4
  - traitlets
  - requests
  - typer
  - pytest
  - emsdk >=3.1.11
  - empack >=2.0.9,<3
  - pip:
      - jupyterlite-core
